// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4RwJGmMpnql0Za5DLpTzdkBYwrPi04Ik',
    appId: '1:108267575769:web:13db8323d019ab8d3ea1c8',
    messagingSenderId: '108267575769',
    projectId: 'campus-connect-324ef',
    authDomain: 'campus-connect-324ef.firebaseapp.com',
    databaseURL: 'https://campus-connect-324ef-default-rtdb.firebaseio.com',
    storageBucket: 'campus-connect-324ef.appspot.com',
    measurementId: 'G-V6LC1J9REQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDabGWE6Aj1ZasOd7tXhPSubQYuC0T-hA0',
    appId: '1:108267575769:android:b261ba3dc70eb6003ea1c8',
    messagingSenderId: '108267575769',
    projectId: 'campus-connect-324ef',
    databaseURL: 'https://campus-connect-324ef-default-rtdb.firebaseio.com',
    storageBucket: 'campus-connect-324ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3b7o9GbLBJ4w31DN3JaOkauQ7OhQS94E',
    appId: '1:108267575769:ios:a22210ba106e6eb33ea1c8',
    messagingSenderId: '108267575769',
    projectId: 'campus-connect-324ef',
    databaseURL: 'https://campus-connect-324ef-default-rtdb.firebaseio.com',
    storageBucket: 'campus-connect-324ef.appspot.com',
    iosClientId: '108267575769-16qg1dqb1hh1oic2emqc04kn8lhgjghf.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3b7o9GbLBJ4w31DN3JaOkauQ7OhQS94E',
    appId: '1:108267575769:ios:40b52021541c3d933ea1c8',
    messagingSenderId: '108267575769',
    projectId: 'campus-connect-324ef',
    databaseURL: 'https://campus-connect-324ef-default-rtdb.firebaseio.com',
    storageBucket: 'campus-connect-324ef.appspot.com',
    iosClientId: '108267575769-o4ej91lg8j18kod8tgkhgocr3ib9tr15.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusConnect.RunnerTests',
  );
}
